name: ${project.build.name}
version: ${project.build.version}
main: info.faceland.bolt.BoltPlugin
depends: [Facecore]

permissions:
  bolt.anylock:
    default: op
  bolt.add:
    default: true
  bolt.remove:
    default: true
  bolt.makenormal:
    default: true
  bolt.setowner:
    default: op

commands:
  locks:
    aliases: [l]